### ISSUE TITLE
Possibly to add toggle for pixel torch

### ISSUE THREAD

**Issue by aayushrautela** [Evolution-XYZ-Devices/packages_apps_PixelParts#13]
Since there is already a slider for Pixel Torch, it would be nice if we can cycle between some predefined values just by tapping the QS style, otherwise, it's not having any usability advantage over the stock torch.
Huge thanks for creating the app.

**Comment by AnierinBliss** [comment]
Done:
https://github.com/Evolution-X-Devices/packages_apps_PixelParts/commit/6b886b3923b75d3a49a47903140e813c360182d8
