### ISSUE TITLE
Question: any reason other pixel devices won't work?

### ISSUE THREAD

**Issue by 306bobby-android** [Evolution-XYZ-Devices/packages_apps_PixelParts#14]
I am the maintainter for crDroid for the pixel 5a. I have issues with hbmsvmanager crashing and want to use pixelparts. Is there a reason it wouldn't work? Does it need gs201/gs101?

**Comment by AnierinBliss** [comment]
You could likely get it to work by changing the node path in Constants.java and updating the selinux policies and init rc cmds to reflect such.
